name: Deploy

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  VERSION: "3.2.7-Community"
  QT_VERSION_WINDOWS: 6.7.2
  EXECUTABLE: "Serial-Studio"
  APPLICATION: "Serial Studio"

jobs:
  build-windows:
    runs-on: windows-latest
    name: '🧊 Windows Build'
    steps:
    - run: git config --global core.autocrlf input

    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: '⚙️ Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{env.QT_VERSION_WINDOWS}}
        host: windows
        target: desktop
        arch: win64_msvc2022_64
        modules: 'qtcharts qtserialport qtserialbus qtwebsockets'
        cache: true

    - name: '⚙️ Install CMake'
      uses: lukka/get-cmake@latest
      with:
        useLocalCache: true

    - name: '🛠 Setup MSVC'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: '⚙️ Download prebuilt gRPC'
      run: |
        gh release download v1.78.1 -R alex-spataru/gRPC-Builds -p "grpc-1.78.1-windows-x86_64.zip"
        7z x grpc-1.78.1-windows-x86_64.zip -o"${{github.workspace}}\grpc-prefix"
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: '🚧 Configure with CMake (GPL Mode)'
      run: |
        cmake -B build `
          -DCMAKE_CXX_COMPILER=cl `
          -DCMAKE_C_COMPILER=cl `
          -DCMAKE_PREFIX_PATH="${{github.workspace}}/grpc-prefix;${{env.Qt6_DIR}}" `
          -DPRODUCTION_OPTIMIZATION=ON `
          -DENABLE_HARDENING=ON `
          -DENABLE_GRPC=ON `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_CONFIGURATION_TYPES=Release `
          -DBUILD_COMMERCIAL=OFF `
          -DBUILD_GPL3=ON

    - name: '🚧 Build application'
      run: cmake --build build --config Release -j 4

    - name: '📦 Create Portable ZIP'
      shell: bash
      run: |
        cd build
        cpack -G ZIP
        mv *.zip ../Serial-Studio-Windows-Portable.zip

    - name: '📤 Upload Result'
      uses: actions/upload-artifact@v4
      with:
        name: Serial-Studio-Free-Version
        path: Serial-Studio-Windows-Portable.zip
